Nb/feat/os encoder
whitesource/BLAST-Remediation-Utils pull request #3
Opened 2021-06-13 13:06 UTC by nadavbarak

2021-06-13 14:41 UTC, shlomieYaniv commented
Please make `mvn spotless:apply` and commit again :)

2021-06-13 15:01 UTC, shlomieYaniv requested changes
Loved the overloading 👍

2021-06-13 15:01 UTC, shlomieYaniv commented on src/main/java/com/whitesource/remediation/encoder/Encode.java
> +    StringBuilder sb = new StringBuilder();
Cool idea to use `StringBuilder`!

2021-06-14 09:37 UTC, nadavbarak commented on src/main/java/com/whitesource/remediation/encoder/Encode.java
> +    return (String[]) results.toArray();
Marked as error on IDE

2021-06-14 09:38 UTC, nadavbarak commented on src/main/java/com/whitesource/remediation/encoder/Encode.java
> +    if (System.getProperty("os.name").toLowerCase().contains("win")) {
Requires an additional dependency of apache

2021-06-15 08:40 UTC, merged